-- liquibase formatted sql
-- changeset k_shvetsova:1 context:create_table
CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR NOT NULL
        CONSTRAINT UQ_COMPILATION_TITLE UNIQUE,
    pinned BOOLEAN DEFAULT false
);
CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT,
    event_id       BIGINT,
    PRIMARY KEY (compilation_id, event_id)
);