-- liquibase formatted sql
-- changeset k_shvetsova:1 context:create_table
CREATE TABLE IF NOT EXISTS notification
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_type  VARCHAR(255)                NOT NULL,
    user_id BIGINT,
    sender_id BIGINT,
    text    varchar,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    read    BOOLEAN                     NOT NULL DEFAULT false
);
